// This file is automatically generated. Do not modify it manually.

package main

var manifest = struct {
	ID      string
	Version string
}{
	ID:      "com.github.rr250.jobpost-plugin",
	Version: "0.0.1",
}
